permalink: /:categories/:title.html
url: "https://Subh94.github.io/blog/"
full_name: "Subhash Kumar Agarwal"
first_name: "Subhash"
last_name: "Agarwal"
blog_title: "From Subhash Pen ....."
author_img_name_path: "/blog/images/users/user.jpg"
disqus_shortname: "Subh94"
copyright_year: "2017"
google_analytics_code: ""
aboutme: "Graduate from IIT Mandi in Computer Science & Engineering with Minor in Management, Tech Lover, Software Developer at Smartron Pvt Ltd,  love to write code and develop product to help society, Have slight Interest in Finance and Economics."
twitter: "AgarwalSk091"
github: "Subh94"
facebook: "sagarwal94"
linkined_url: "https://www.linkedin.com/in/subhashka/"
